import type { Metadata } from "next";
import { Geist } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header/Header";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import QueryProvider from "@/reactQuery/queryProvider";
import { AuthProvider } from "@/auth/AuthProvider";
import Footer from "@/components/footer/Footer";

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist",
  display: "swap",
});

const geo1 = localFont({
  src: "../../fonts/geo1.otf",
  variable: "--font-geo1",
  display: "swap",
  weight: "400",
});

const geo2 = localFont({
  src: "../../fonts/geo2.ttf",
  variable: "--font-geo2",
  display: "swap",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  locale,
}: Readonly<{
  children: React.ReactNode;
  locale: string;
}>) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${geist.variable} ${geo1.variable} ${geo2.variable}`}>
        <AuthProvider>
          <QueryProvider>
            <NextIntlClientProvider messages={messages}>
              <Header />
              {children}
              <Footer />
            </NextIntlClientProvider>
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}